### ISSUE TITLE
Refine Draft Model: How to use?

### ISSUE THREAD

**Issue by Gerkinfeltser** [VAST-AI-Research/ComfyUI-Tripo#10]
When using the refine model, I don't see anyway to extract the mesh either to a Tripo: GLB Viewer or otherwise. How does it work?
![image](https://github.com/user-attachments/assets/9fc5d120-c49f-4484-9ab5-e42a2064ee96)

The [refine_model.png](https://github.com/VAST-AI-Research/ComfyUI-Tripo/blob/main/workflows/refine_model.png) & [retarget.png](https://github.com/VAST-AI-Research/ComfyUI-Tripo/blob/main/workflows/retarget.png) workflows included in the repository appear to be images both showing retargeting workflows. (Differences being the contained nodes positioning  & "Tripo: Rig Draft Model" having an extra input.)

Thank you!

**Comment by seed93** [comment]
Thanks. Fixed
