### ISSUE TITLE
上传图片点击生成后，后台一直不执行停留在

### ISSUE THREAD

**Issue by DamienCz** [VAST-AI-Research/ComfyUI-Tripo#14]
上传图片点击生成后，后台一直不执行停留在
Submitting task: image_to_model
Task file type: jpg
Task ID:xxxxxxxxxxxxxxxxxxxxxxxxx这一步
但tripo后台显示已生成成功
![image](https://github.com/user-attachments/assets/39509522-7189-4cbe-b25a-51bb79d94e4a)

**Comment by DamienCz** [comment]
OK 经过十五分钟他终于出来了，这很奇怪，不应该这么慢啊

**Comment by seed93** [comment]
Now it should work
