### ISSUE TITLE
Cannot execute because a node is missing the class_type property.: Node ID '#9'

### ISSUE THREAD

**Issue by cinxiang** [VAST-AI-Research/ComfyUI-Tripo#15]
Tripo:Generate Draft model节点有问题，加载不上，我确定API_Key设置是对的，也可以正确返回结果，但在Comfyui里就是无法使用，请告诉我这是什么错误？
<img width="566" alt="1" src="https://github.com/user-attachments/assets/33ed9d93-1d73-4999-b785-f0634e54747d">

**Comment by seed93** [comment]
Please update to the newest version and try again.

**Comment by seed93** [comment]
Are you still having this issue?
