### ISSUE TITLE
Error "NoneType" object is not subscriptable!

### ISSUE THREAD

**Issue by merecesarchviz** [VAST-AI-Research/ComfyUI-Tripo#16]
Always i try to do img to 3d i got this error!! any know how to solve it?

![dfdg](https://github.com/user-attachments/assets/7f07a724-9a6d-4437-a79c-c6d0d62855cb)

**Comment by merecesarchviz** [comment]
> Could you please try again? We fixed an issue maybe related to this.

I test it and i still got the exactly same problem!?

![imagem](https://github.com/user-attachments/assets/548c19d6-c565-470b-a6b0-5baa05de9311)

**Comment by seed93** [comment]
I am not sure what happened to you. Do you have this issue all the time?

**Comment by merecesarchviz** [comment]
> I am not sure what happened to you. Do you have this issue all the time?

yes when i do a generate, i got always that error! I´m not able to use the node!

**Comment by seed93** [comment]
> > I am not sure what happened to you. Do you have this issue all the time?
> 
> yes when i do a generate, i got always that error! I´m not able to use the node!

I  cannot reproduce your case. Could you please the latest version and attach your log? There is an error in `_receive_one` function and I need your help.
