### ISSUE TITLE
Tripo RETARGET generates error | TypeError: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by v1s10n-t4rb4ll** [VAST-AI-Research/ComfyUI-Tripo#18]
2024-10-01 11:17:12,299 - root - INFO - got prompt
2024-10-01 11:18:34,269 - root - ERROR - !!! Exception during processing !!! a bytes-like object is required, not 'int'
2024-10-01 11:18:34,270 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 49, in display
    f.write(single_mesh)
TypeError: a bytes-like object is required, not 'int'

2024-10-01 11:18:34,290 - root - INFO - Prompt executed in 81.98 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":18,"nodes":[{"id":10,"type":"TripoGLBViewer","pos":{"0":331,"1":323},"size":[600,500],"flags":{},"order":2,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":9,"slot_index":0}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":11,"type":"TripoGLBViewer","pos":{"0":997,"1":327},"size":[600,500],"flags":{},"order":4,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":10}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":7,"type":"LoadImage","pos":{"0":254,"1":938},"size":{"0":210,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[8],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Screenshot (5469).png","image"]},{"id":9,"type":"TripoAPIDraft","pos":{"0":531,"1":1033},"size":{"0":400,"1":308},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":8,"slot_index":0},{"name":"image_lr","type":"IMAGE","link":null},{"name":"image_back","type":"IMAGE","link":null}],"outputs":[{"name":"MESH","type":"MESH","links":[9],"slot_index":0,"shape":3},{"name":"MODEL_TASK_ID","type":"MODEL_TASK_ID","links":[7],"slot_index":1,"shape":3},{"name":"API_KEY","type":"API_KEY","links":[13,16],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"TripoAPIDraft"},"widgets_values":["image_to_model","APIKEY_NUMBER_REPLACED","","LEFT",false,"v1.4-20240625",0,0,0]},{"id":8,"type":"TripoAnimateRigNode","pos":{"0":1095,"1":977},"size":{"0":430.8000183105469,"1":46},"flags":{},"order":3,"mode":0,"inputs":[{"name":"original_model_task_id","type":"MODEL_TASK_ID","link":7,"slot_index":0},{"name":"apikey","type":"API_KEY","link":13}],"outputs":[{"name":"MESH","type":"MESH","links":[10],"slot_index":0,"shape":3},{"name":"RIG_TASK_ID","type":"RIG_TASK_ID","links":[15],"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRigNode"},"widgets_values":[]},{"id":14,"type":"TripoAnimateRetargetNode","pos":{"0":1641,"1":1069},"size":{"0":342.5999755859375,"1":78},"flags":{},"order":5,"mode":0,"inputs":[{"name":"original_model_task_id","type":"RIG_TASK_ID","link":15},{"name":"apikey","type":"API_KEY","link":16}],"outputs":[{"name":"MESH","type":"MESH","links":[18],"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRetargetNode"},"widgets_values":["preset:walk"]},{"id":15,"type":"TripoGLBViewer","pos":{"0":1667,"1":328},"size":[600,500],"flags":{},"order":6,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":18}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]}],"links":[[7,9,1,8,0,"MODEL_TASK_ID"],[8,7,0,9,0,"IMAGE"],[9,9,0,10,0,"MESH"],[10,8,0,11,0,"MESH"],[13,9,2,8,1,"API_KEY"],[15,8,1,14,0,"RIG_TASK_ID"],[16,9,2,14,1,"API_KEY"],[18,14,0,15,0,"MESH"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[-117.08999999999988,-225.6999999999999]}},"version":0.4}
```

## Additional Context
Using this workflow (I have to connect the API-KEY to the rig and retarget nodes), the error always occurs:
https://github.com/VAST-AI-Research/ComfyUI-Tripo/blob/main/workflows/retarget.png

I have not been able to successfully generate animation from this workflow.

**Comment by seed93** [comment]
> 2024-10-01 11:17:12,299 - root - INFO - got prompt 2024-10-01 11:18:34,269 - root - ERROR - !!! Exception during processing !!! a bytes-like object is required, not 'int' 2024-10-01 11:18:34,270 - root - ERROR - Traceback (most recent call last): File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tripo__init__.py", line 49, in display f.write(single_mesh) TypeError: a bytes-like object is required, not 'int'
> 
> 2024-10-01 11:18:34,290 - root - INFO - Prompt executed in 81.98 seconds
> 
> ```
> ## Attached Workflow
> Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
> ```
> 
> {"last_node_id":15,"last_link_id":18,"nodes":[{"id":10,"type":"TripoGLBViewer","pos":{"0":331,"1":323},"size":[600,500],"flags":{},"order":2,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":9,"slot_index":0}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":11,"type":"TripoGLBViewer","pos":{"0":997,"1":327},"size":[600,500],"flags":{},"order":4,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":10}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":7,"type":"LoadImage","pos":{"0":254,"1":938},"size":{"0":210,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[8],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Screenshot (5469).png","image"]},{"id":9,"type":"TripoAPIDraft","pos":{"0":531,"1":1033},"size":{"0":400,"1":308},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":8,"slot_index":0},{"name":"image_lr","type":"IMAGE","link":null},{"name":"image_back","type":"IMAGE","link":null}],"outputs":[{"name":"MESH","type":"MESH","links":[9],"slot_index":0,"shape":3},{"name":"MODEL_TASK_ID","type":"MODEL_TASK_ID","links":[7],"slot_index":1,"shape":3},{"name":"API_KEY","type":"API_KEY","links":[13,16],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"TripoAPIDraft"},"widgets_values":["image_to_model","APIKEY_NUMBER_REPLACED","","LEFT",false,"v1.4-20240625",0,0,0]},{"id":8,"type":"TripoAnimateRigNode","pos":{"0":1095,"1":977},"size":{"0":430.8000183105469,"1":46},"flags":{},"order":3,"mode":0,"inputs":[{"name":"original_model_task_id","type":"MODEL_TASK_ID","link":7,"slot_index":0},{"name":"apikey","type":"API_KEY","link":13}],"outputs":[{"name":"MESH","type":"MESH","links":[10],"slot_index":0,"shape":3},{"name":"RIG_TASK_ID","type":"RIG_TASK_ID","links":[15],"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRigNode"},"widgets_values":[]},{"id":14,"type":"TripoAnimateRetargetNode","pos":{"0":1641,"1":1069},"size":{"0":342.5999755859375,"1":78},"flags":{},"order":5,"mode":0,"inputs":[{"name":"original_model_task_id","type":"RIG_TASK_ID","link":15},{"name":"apikey","type":"API_KEY","link":16}],"outputs":[{"name":"MESH","type":"MESH","links":[18],"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRetargetNode"},"widgets_values":["preset:walk"]},{"id":15,"type":"TripoGLBViewer","pos":{"0":1667,"1":328},"size":[600,500],"flags":{},"order":6,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":18}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]}],"links":[[7,9,1,8,0,"MODEL_TASK_ID"],[8,7,0,9,0,"IMAGE"],[9,9,0,10,0,"MESH"],[10,8,0,11,0,"MESH"],[13,9,2,8,1,"API_KEY"],[15,8,1,14,0,"RIG_TASK_ID"],[16,9,2,14,1,"API_KEY"],[18,14,0,15,0,"MESH"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[-117.08999999999988,-225.6999999999999]}},"version":0.4}
> 
> ```
> 
> ## Additional Context
> Using this workflow (I have to connect the API-KEY to the rig and retarget nodes), the error always occurs:
> https://github.com/VAST-AI-Research/ComfyUI-Tripo/blob/main/workflows/retarget.png
> 
> I have not been able to successfully generate animation from this workflow.
> ```

Thanks. Fixed now.
