### ISSUE TITLE
tripoSR (old model) for free, without using api?

### ISSUE THREAD

**Issue by placeboyue** [VAST-AI-Research/ComfyUI-Tripo#19]
(not really an issue or bug, sorry) is it possible? 
"flowty" is broken (at least for me) only this one works, and from what i can tell (the tutorial doesn't explain this) i need an API key even if i select the older model? and it'll still charge me credits?

i would like to run the older model locally, so even if tripo allows us to use it for free with their API and whatnot, i'd like to be able to run it without api keys and stuff. Future-proof, you know? i don't wanna rely on something that might break in a month or a year.
Thank you.

**Comment by seed93** [comment]
Tripo is a product while triposr is opensource and could be run locally. They are totally different and should be used separatedly. Thanks.
