### ISSUE TITLE
output always overwrites previous output-file, does not generate a new file

### ISSUE THREAD

**Issue by v1s10n-t4rb4ll** [VAST-AI-Research/ComfyUI-Tripo#20]
## I have tried making a "mesh_00082_.glb" but TRIPO just overwrites mesh_00081 for some reason...

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt

Submitting task: image_to_model
Task file type: jpg
Task ID: 3742f1c2-8087-420e-a68d-62888216fd44
Task completed successfully.
Downloading model: https://tripo-data.cdn.bcebos.com/[Client ID REMOVED]/20241004/3742f1c2-8087-420e-a68d-62888216fd44/tripo_pbr_model_3742f1c2-8087-420e-a68d-62888216fd44.glb?auth_key=1728010849-mcacL1Br-0-5f7c5b1eb06d9f41df9761f280eda357
Saved GLB file to D:\ComfyUI_windows_portable\ComfyUI\output\/mesh_00081_.glb
Submitting task: refine_model
Task draft model task ID: 3742f1c2-8087-420e-a68d-62888216fd44
!!! Exception during processing !!! Failed to generate mesh: The original task is not a valid task
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 140, in generate_mesh
    raise RuntimeError(f"Failed to generate mesh: {result['message']}")
RuntimeError: Failed to generate mesh: The original task is not a valid task

Prompt executed in 62.14 seconds

**Comment by seed93** [comment]
It was shown in log that you refined a v2.0 model, which is not suppoted. I am not sure if this caused the overwrite problem.

**Comment by v1s10n-t4rb4ll** [comment]
The overwrite issue occurs continuously (even not using v2.0)

**Comment by v1s10n-t4rb4ll** [comment]
Also note, previously, it was saving my meshes as:
meshsave_000XX_.glb

Then, around the beginning of October, it changed the save file to:
mesh_000XX_.glb

---> This occurs regardless if I use v1.4 or v2.x

**Comment by seed93** [comment]
I renamed the mesh, and hope this could solve your issue
