### ISSUE TITLE
RuntimeError: Failed to generate mesh: The original task is not a valid task

### ISSUE THREAD

**Issue by v1s10n-t4rb4ll** [VAST-AI-Research/ComfyUI-Tripo#21]
2024-10-03 23:19:37,371 - root - INFO - Starting server

2024-10-03 23:19:37,371 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-03 23:20:06,401 - root - INFO - got prompt
2024-10-03 23:21:10,947 - root - ERROR - !!! Exception during processing !!! Failed to generate mesh: The original task is not a valid task
2024-10-03 23:21:10,948 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 140, in generate_mesh
    raise RuntimeError(f"Failed to generate mesh: {result['message']}")
RuntimeError: Failed to generate mesh: The original task is not a valid task

2024-10-03 23:21:10,949 - root - INFO - Prompt executed in 64.54 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":26,"last_link_id":28,"nodes":[{"id":21,"type":"TripoAnimateRetargetNode","pos":{"0":2346,"1":1283},"size":{"0":352.79998779296875,"1":78},"flags":{},"order":7,"mode":0,"inputs":[{"name":"original_model_task_id","type":"RIG_TASK_ID","link":22},{"name":"apikey","type":"API_KEY","link":24}],"outputs":[{"name":"MESH","type":"MESH","links":[23],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRetargetNode"},"widgets_values":["preset:walk"]},{"id":19,"type":"TripoRefineModel","pos":{"0":1484,"1":1052},"size":{"0":342.5999755859375,"1":46},"flags":{},"order":3,"mode":0,"inputs":[{"name":"model_task_id","type":"MODEL_TASK_ID","link":18,"slot_index":0},{"name":"apikey","type":"API_KEY","link":19}],"outputs":[{"name":"MESH","type":"MESH","links":[26],"slot_index":0,"shape":3},{"name":"MODEL_TASK_ID","type":"MODEL_TASK_ID","links":[20],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"TripoRefineModel"},"widgets_values":[]},{"id":20,"type":"TripoAnimateRigNode","pos":{"0":1901,"1":1129},"size":{"0":430.8000183105469,"1":46},"flags":{},"order":5,"mode":0,"inputs":[{"name":"original_model_task_id","type":"MODEL_TASK_ID","link":20},{"name":"apikey","type":"API_KEY","link":21}],"outputs":[{"name":"MESH","type":"MESH","links":[27],"slot_index":0,"shape":3},{"name":"RIG_TASK_ID","type":"RIG_TASK_ID","links":[22],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"TripoAnimateRigNode"},"widgets_values":[]},{"id":22,"type":"TripoGLBViewer","pos":{"0":2925,"1":1296},"size":[600,500],"flags":{},"order":8,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":23}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":25,"type":"TripoGLBViewer","pos":{"0":2865,"1":670},"size":[600,500],"flags":{},"order":6,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":27}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":24,"type":"TripoGLBViewer","pos":{"0":2128,"1":492},"size":[600,500],"flags":{},"order":4,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":26}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":26,"type":"TripoGLBViewer","pos":{"0":1457,"1":397},"size":[600,500],"flags":{},"order":2,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":28}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":7,"type":"LoadImage","pos":{"0":785,"1":988},"size":{"0":313.6480407714844,"1":434.7273254394531},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["q23433a.jpg","image"]},{"id":14,"type":"TripoAPIDraft","pos":{"0":1170,"1":1062},"size":{"0":264,"1":311},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":13,"slot_index":0},{"name":"image_lr","type":"IMAGE","link":null},{"name":"image_back","type":"IMAGE","link":null}],"outputs":[{"name":"MESH","type":"MESH","links":[28],"slot_index":0,"shape":3},{"name":"MODEL_TASK_ID","type":"MODEL_TASK_ID","links":[18],"shape":3},{"name":"API_KEY","type":"API_KEY","links":[19,21,24],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"TripoAPIDraft"},"widgets_values":["image_to_model","APIKEY_NUMBER_REPLACED","","RIGHT",false,"v2.0-20240919",0,0,0]}],"links":[[13,7,0,14,0,"IMAGE"],[18,14,1,19,0,"MODEL_TASK_ID"],[19,14,2,19,1,"API_KEY"],[20,19,1,20,0,"MODEL_TASK_ID"],[21,14,2,20,1,"API_KEY"],[22,20,1,21,0,"RIG_TASK_ID"],[23,21,0,22,0,"MESH"],[24,14,2,21,1,"API_KEY"],[26,19,0,24,0,"MESH"],[27,20,0,25,0,"MESH"],[28,14,0,26,0,"MESH"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650706,"offset":[-813.455119999998,-333.8830400000004]}},"version":0.4}
```

## Additional Context
Trying to use model version v2.0-20240919

**Comment by MagLilyPitts** [comment]
Also receiving this error.

**Comment by seed93** [comment]
I think you refined a model generated by model_version 2.0, which is not supported.
