### ISSUE TITLE
TripoAPIDraft ,报错，Failed to generate mesh: Authentication failed

### ISSUE THREAD

**Issue by ruoxuer** [VAST-AI-Research/ComfyUI-Tripo#24]
Submitting task: text_to_model
Task prompt: A turtle master, a-pose
!!! Exception during processing !!! Failed to generate mesh: Authentication failed
Traceback (most recent call last):
  File "F:\AI\01NewcomfyUI\ComfyUI202426\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\01NewcomfyUI\ComfyUI202426\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\01NewcomfyUI\ComfyUI202426\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\01NewcomfyUI\ComfyUI202426\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\01NewcomfyUI\ComfyUI202426\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 105, in generate_mesh
    raise RuntimeError(f"Failed to generate mesh: {result['message']}")
RuntimeError: Failed to generate mesh: Authentication failed

Prompt executed in 1.84 seconds

=======================================
我确定我填写了正确的APIkey在config.json，以及comfy的节点 上也填了，都不行。

**Comment by seed93** [comment]
The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.

**Comment by ruoxuer** [comment]
> The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。

是的，我的API是以tsk_开头的。

**Comment by ruoxuer** [comment]
> The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。

OK了，原来是要点一下密钥旁边的刷新图标。

**Comment by ruoxuer** [comment]
> The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。

OK了，已解决，非常感谢！！！！

**Comment by ruoxuer** [comment]
> The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。

请问模型只能是glb的吗？能支持回传的模型是fbx或者obj格式的吗？

**Comment by ruoxuer** [comment]
> > The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。API密钥是一个以“tsk_”开头的字符串，您可以使用platform.tripo3d.ai上的示例来验证API密钥。API密钥是一个以“tsk_”开头的字符串，您可以使用platform.tripo3d可以.ai 上的示例来验证 API 密钥。
> 
> 请问模型只能是glb的吗？能支持回传的模型是fbx或者obj格式的吗？

在py文件中看到了，找到了obj的转换节点，谢谢谢谢，

**Comment by seed93** [comment]
> > The API key is a string that starts with "tsk_," and you can validate the API key using the example on platform.tripo3d.ai.API 密钥是一个以“tsk_”开头的字符串，您可以使用 platform.tripo3d.ai 上的示例来验证 API 密钥。
> 
> 请问模型只能是glb的吗？能支持回传的模型是fbx或者obj格式的吗？

Please use convert node to get fbx or other formats.
