### ISSUE TITLE
在浏览器控制台出现 Cannot read properties of undefined (reading 'display')的错误，导致节点无法加载

### ISSUE THREAD

**Issue by zjf2671** [VAST-AI-Research/ComfyUI-Tripo#26]
![1729846676051](https://github.com/user-attachments/assets/189b0164-20e5-4279-a64f-de7693ae6e92)

use_everywhere.js:283 TypeError: Cannot read properties of undefined (reading 'display')
    at createIntWidget (widgets.ts:297:40)
    at Object.INT (widgets.ts:422:12)
    at new ComfyNode (app.ts:2043:40)
    at LiteGraphGlobal.createNode (litegraph.es.js:2362:17)
    at LiteGraph.createNode (use_everywhere.js:283:35)
    at HTMLDivElement.callback (extensions-LpJhrTUa.js:1:66511)
    at HTMLDivElement.l (extensions-LpJhrTUa.js:1:71623)
createNode @ litegraph.es.js:2364
LiteGraph.createNode @ use_everywhere.js:283
callback @ extensions-LpJhrTUa.js:1
l @ extensions-LpJhrTUa.js:1
Show 1 more frame

当我加载Generate Draft model 这个节点的时候 ,   在浏览器控制台出现上面的错误，导致节点无法加载。
但Tripo的别的节点都能加载正常

**Comment by seed93** [comment]
Are you using the workflow images from readme? I have updated the images, please have a try.

**Comment by seed93** [comment]
What is you comfyui version?

**Comment by zjf2671** [comment]
> What is you comfyui version?

![image](https://github.com/user-attachments/assets/10b3a75b-e94f-4e62-a7a3-249ce6b46ffe)

**Comment by seed93** [comment]
I reproduced your case and fixed it. It only happens in newer version. Thanks
