### ISSUE TITLE
Failed to generate mesh: The original task type is not supported

### ISSUE THREAD

**Issue by icegrold** [VAST-AI-Research/ComfyUI-Tripo#30]
Hello, I encountered this error when using the 2.0 model generation, is the 1.4 version of the model missing, please tell me how I should solve this problem.
<img width="365" alt="93b95e06a5761cf35bab366e9096a4b" src="https://github.com/user-attachments/assets/29c1c462-6910-4e59-8435-ff16ab9816b6">

**Comment by seed93** [comment]
Refine for 2.0 model is not supported or needed.-------- 原始邮件 --------发件人： icegrold ***@***.***>日期： 2024年11月7日周四 07:38收件人： VAST-AI-Research/ComfyUI-Tripo ***@***.***>抄送： Subscribed ***@***.***>主    题： [VAST-AI-Research/ComfyUI-Tripo] Failed to generate mesh: The original task type is not supported (Issue #30)
Hello, I encountered this error when using the 2.0 model generation, is the 1.4 version of the model missing, please tell me how I should solve this problem.
32486f1d488560aed484a764d438197.jpg (view on web)
