### ISSUE TITLE
Error Repot : TripoAPIDraft An error occurred: server rejected WebSocket connection: HTTP 426

### ISSUE THREAD

**Issue by DruidTin** [VAST-AI-Research/ComfyUI-Tripo#34]
# ComfyUI Error Report
## Error Details
- **Node Type:** TripoAPIDraft
- **Exception Type:** Exception
- **Exception Message:** An error occurred: server rejected WebSocket connection: HTTP 426
## Stack Trace

When I execute the Queue Prompt, this error report appears. However, it was working fine before November 23. Could it be an issue with Tripo updating their service protocols?

**Comment by seed93** [comment]
Did you upgrade anything? We did not change the service protocol. Could you please try again and provide further information?发自我的手机-------- 原始邮件 --------发件人： Druid Ting ***@***.***>日期： 2024年11月23日周六 16:10收件人： VAST-AI-Research/ComfyUI-Tripo ***@***.***>抄送： Subscribed ***@***.***>主    题： [VAST-AI-Research/ComfyUI-Tripo] Error Repot : TripoAPIDraft An error occurred: server rejected WebSocket connection: HTTP 426 (Issue #34)
ComfyUI Error Report
Error Details
Node Type: TripoAPIDraftException Type: ExceptionException Message: An error occurred: server rejected WebSocket connection: HTTP 426
Stack Trace
When I execute the Queue Prompt, this error report appears. However, it was working fine before November 23. Could it be an issue with Tripo updating their service protocols?

**Comment by emilune** [comment]
Hello, same problem and error message here.

**Comment by seed93** [comment]
I see. We will fix it asap发自我的手机-------- 原始邮件 --------发件人： emilune ***@***.***>日期： 2024年11月23日周六 18:25收件人： VAST-AI-Research/ComfyUI-Tripo ***@***.***>抄送： seed93 ***@***.***>, Comment ***@***.***>主    题： Re: [VAST-AI-Research/ComfyUI-Tripo] Error Repot : TripoAPIDraft An error occurred: server rejected WebSocket connection: HTTP 426 (Issue #34)
Hello, same problem and error message here.

**Comment by seed93** [comment]
It should be fixed now发自我的手机-------- 原始邮件 --------发件人： emilune ***@***.***>日期： 2024年11月23日周六 18:25收件人： VAST-AI-Research/ComfyUI-Tripo ***@***.***>抄送： seed93 ***@***.***>, Comment ***@***.***>主    题： Re: [VAST-AI-Research/ComfyUI-Tripo] Error Repot : TripoAPIDraft An error occurred: server rejected WebSocket connection: HTTP 426 (Issue #34)
Hello, same problem and error message here.

**Comment by emilune** [comment]
Yes, it is. Thanks.
